/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    BlogCategoryCard: typeof import('./src/components/Home/BlogCategoryCard.vue')['default']
    CategoryCard: typeof import('./src/components/Course/CategoryCard.vue')['default']
    ClassroomPreview: typeof import('./src/components/CourseDetail/ClassroomPreview.vue')['default']
    CourseOverview: typeof import('./src/components/CourseDetail/CourseOverview.vue')['default']
    CourseSidebar: typeof import('./src/components/CourseDetail/CourseSidebar.vue')['default']
    CreatorCard: typeof import('./src/components/Search/CreatorCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FeatureCard: typeof import('./src/components/Membership/FeatureCard.vue')['default']
    FeaturedBlogCard: typeof import('./src/components/Home/FeaturedBlogCard.vue')['default']
    LearningPlatform: typeof import('./src/components/Search/LearningPlatform.vue')['default']
    LearningProgressCard: typeof import('./src/components/Course/LearningProgressCard.vue')['default']
    MarketingContentCard: typeof import('./src/components/Home/MarketingContentCard.vue')['default']
    MembershipBanner: typeof import('./src/components/Membership/MembershipBanner.vue')['default']
    PricingSection: typeof import('./src/components/Membership/PricingSection.vue')['default']
    RatingProgress: typeof import('./src/components/CourseDetail/RatingProgress.vue')['default']
    RecommendedCourseCard: typeof import('./src/components/Course/RecommendedCourseCard.vue')['default']
    RemoteLearningDesc: typeof import('./src/components/Membership/RemoteLearningDesc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndFilter: typeof import('./src/components/Search/SearchAndFilter.vue')['default']
    SearchResult: typeof import('./src/components/Search/SearchResult.vue')['default']
    StudentsCommentCard: typeof import('./src/components/Membership/StudentsCommentCard.vue')['default']
    StudentsSay: typeof import('./src/components/Search/StudentsSay.vue')['default']
    TheFooter: typeof import('./src/components/Layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/Layout/TheHeader.vue')['default']
    TopEducationCard: typeof import('./src/components/CourseDetail/TopEducationCard.vue')['default']
  }
}
